### ISSUE TITLE
Make production ready

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#10]
* Transpile ES2015 to ES5 using Babel
* Add `promises` and `fetch` polyfills
* Minify CSS/JS
* JPEGify images

**Comment by ManjotS** [comment]
Deploy script will handle minifying and compressing of css/js/images. 

Just keep dev full source

**Comment by bogas04** [comment]
I think we are doing good here. Babel + polyfills are in place. Closing now. Please re-open if there's anything you feel we need to change.

@navdeepsinghkhalsa @ManjotS
