### ISSUE TITLE
Drop body_text in favor of breadcrumb navigation

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#101]
IMO it's very off putting.

| Before | After |
| :------: | :-----: |
| ![before](https://cloud.githubusercontent.com/assets/6177621/23691808/e02d7158-03f0-11e7-843d-34c6dd93dd38.png) | ![after](https://cloud.githubusercontent.com/assets/6177621/23691980/e8f61d2a-03f1-11e7-9b5f-4d5e45de87cf.png) |

Code:
```html

<style>
  .breadcrumb {
    padding: 0 0.5rem;
    margin: 1rem 3rem;
    font-size: .8rem;
  }
  .breadcrumb ul {
    list-style: none;
  }
  .breadcrumb li::after {
      content: ">>";
      display: inline;
      margin: 0 9px;
  }
</style>
<div class="breadcrumb">
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="">Random Shabad</a></li>
  </ul>
</div>
```

**Comment by bogas04** [comment]
@ManjotS What do you think ?

**Comment by navdeepsinghkhalsa** [comment]
@bogas04 I agree that the body text doesn't look good. Breadcrumbs is a fine idea, but may not be necessary. Random will be redirected to the actual Shabad instead of being its own page. Please see #99

**Comment by bogas04** [comment]
@navdeepsinghkhalsa Oh I see. There are two pages that might require it, hukamnama and random. Random as per #99 might just be another shabad page. 

Maybe we can have it for hukamnama?

**Comment by ManjotS** [comment]
I like it, please do it, but keep in mind #99 . Lets get the ticket queue down! :D

**Comment by bogas04** [comment]
This is how it looks now.

Before | After
|:--|:--
<img width="1348" alt="screen shot 2018-03-18 at 9 36 27 pm" src="https://user-images.githubusercontent.com/6177621/37567960-7f896236-2af4-11e8-93a7-5c6b4a4648ae.png"> | <img width="1367" alt="screen shot 2018-03-18 at 9 35 49 pm" src="https://user-images.githubusercontent.com/6177621/37567955-5c8afb96-2af4-11e8-8ff2-6a06bf16ff16.png">
<img width="1320" alt="screen shot 2018-03-18 at 9 35 32 pm" src="https://user-images.githubusercontent.com/6177621/37567975-cb3ef146-2af4-11e8-914b-b18233a1d551.png"> |<img width="1339" alt="screen shot 2018-03-18 at 9 36 39 pm" src="https://user-images.githubusercontent.com/6177621/37567962-8bd82752-2af4-11e8-95f0-17d5bb73408b.png">
