### ISSUE TITLE
document with comments in source h.js

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#102]
what does it do?

**Comment by ManjotS** [comment]
`cat /tmp/ang.patch.sql 
--
-- Dumping data for table `settings`
--
-- WHERE:  id = 2

use sttm_dev;

DELETE FROM `settings` WHERE id=2;
INSERT INTO `settings` VALUES (2,'search_types','{\n	\"0\": \"First Letter Start (Gurmukhi)\",\n	\"1\": \"First Letter Anywhere (Gurmukhi)\",\n	\"2\": \"Full Word (Gurakhar)\",\n	\"3\": \"Full Word (English)\",\n	\"4\": \"Romanized (English)\",\n       \"5\": \"Ang\"\n}');

-- Dump completed on 2017-03-11 16:21:35
`

patch to add to drop down

**Comment by tarunsingh5** [comment]
no longer relevant
