### ISSUE TITLE
English transliterations on by default

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#104]
User complaints are coming in that we don't have transliterations anymore. Turn on by default.

**Comment by ManjotS** [comment]
@navdeepsinghkhalsa @bogas04 this needs to be high priority as we have at least 10 user complaints.

**Comment by tarunsingh5** [comment]
I havent heard any complaints on this in the last few months - can we drop?

**Comment by tarunsingh5** [comment]
This is fixed
