### ISSUE TITLE
AddThis integration

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#106]
Should be available for whole url/sttm page for:
search
shabad
ang

**Comment by navdeepsinghkhalsa** [comment]
@ManjotS Could you please elaborate?

**Comment by ManjotS** [comment]
http://www.addthis.com/

Sharing

**Comment by ManjotS** [comment]
I am working on an implementation that doesnt use addthis or sharethis because they are not what they used to be.

**Comment by ManjotS** [comment]
its on dev
