### ISSUE TITLE
Share buttons overlap Gurbani

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/SikhiToTheMax-Web#108]
Share buttons currently open lap Gurbani when reading a shabad.

**Comment by ManjotS** [comment]
im not sure this is a bug. I think the bug is more that it stickies when you tap a line on mobile.

**Comment by ManjotS** [comment]
Got another user report on this: 
Could you please get rid of the twitter and copy thing on the tuk when I read it on the mobile please?

**Comment by ManjotS** [comment]
I suggest that we consider removing the single line one from mobile or make it so they have to swipe the bani or long press on it

**Comment by bogas04** [comment]
Closing it as we don't show Share buttons on mobile now and the buttons are only visible on hover on desktop.
