### ISSUE TITLE
Add clipboard to top share icons

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#109]
Should be able to copy all gurbani on page.. ideally in rtf

**Comment by bogas04** [comment]
Copy button copies the short link to shabad. Maybe fixing #183 is good enough for now?

**Comment by ManjotS** [comment]
183 is good, but then use that to also add to clipboard for this ticket

**Comment by tarunsingh5** [comment]
dont think we need this as it would clutter the UI and we already have too many buttons imo

**Comment by ManjotS** [comment]
https://fontawesome.com/icons/clipboard?style=solid

**Comment by ManjotS** [comment]
fa-clipboard

**Comment by bogas04** [comment]
What about the other clipboard button we have? Maybe we should convert it into an input with inset button?

**Comment by ManjotS** [comment]
Ask Aman singh

**Comment by bogas04** [comment]
@saintsoldierx  @ManjotS  @tarunsingh5  @prebhdevsingh 

This is how sharing is now:

Desktop mode: Embed | Copy All | Copy Short Link
Mobile mode: WhatsApp | Copy All | Copy Short Link
Mobile (with web share): Share | Copy All | Copy Short Link

Dark Mode | Normal Mode
|:--|:--
<img width="538" alt="screen shot 2018-05-01 at 8 40 06 pm" src="https://user-images.githubusercontent.com/6177621/39478394-f38c2706-4d7f-11e8-8c88-ee3c5272f4db.png"> | <img width="438" alt="screen shot 2018-05-01 at 8 40 31 pm" src="https://user-images.githubusercontent.com/6177621/39478398-f428e10e-4d7f-11e8-9b1b-a0e1fb6b4eee.png">
<img width="475" alt="screen shot 2018-05-01 at 8 40 18 pm" src="https://user-images.githubusercontent.com/6177621/39478395-f3b40028-4d7f-11e8-9e15-d9f9f17e748c.png"> | <img width="477" alt="screen shot 2018-05-01 at 8 40 26 pm" src="https://user-images.githubusercontent.com/6177621/39478397-f3e04d72-4d7f-11e8-9ee1-91b468c7322e.png">
