### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#116]
This should be replaced with the following:

- [ ] When this occurs it should be logged to the server with an incident ID and stack trace
- [ ] If its infrequent enough, we should receive an alert
- [x] An explanation of what the app was trying to do should be displayed
- [x] Some sort of friendly character different from 404 could be displayed
- [ ] Contact form and/or contact link should be displayed

**Comment by bogas04** [comment]
Do we have cute images for non-happy flows?

* Empty search string
* 404 (we already have a Bhai Jee)
* Random Error 
* No results (edited)

**Comment by ManjotS** [comment]
bhai is balpreet singh - use him for random error, server timeout and you're not online

**Comment by ManjotS** [comment]
![sachkaur](https://user-images.githubusercontent.com/644885/37617948-c9cad55a-2b71-11e8-83e6-be9e99bed2ba.png)
sach kaur for the rest

**Comment by bogas04** [comment]
| Error | Image |
|:--|:--|
| Generic Error | <img width="1440" alt="screen shot 2018-03-25 at 5 52 46 pm" src="https://user-images.githubusercontent.com/6177621/37874906-6043d954-3055-11e8-8a40-9b106628db2d.png">
| No results | <img width="1440" alt="screen shot 2018-03-25 at 5 52 30 pm" src="https://user-images.githubusercontent.com/6177621/37874907-60818f6a-3055-11e8-8582-4959f7b55c43.png">
| Empty Search String | <img width="1439" alt="screen shot 2018-03-25 at 5 52 22 pm" src="https://user-images.githubusercontent.com/6177621/37874908-60b9d028-3055-11e8-9699-9e3d65cbfb85.png">

**Comment by bogas04** [comment]
Query follows the font now (type=3,4 englis, otherwise gurbani-font).
Also added some `margin-bottom` to image in mobile view.

**Comment by ManjotS** [comment]
Yeah it's awesome
