### ISSUE TITLE
refactor js helper functions and display functions

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#119]
~~- [ ] Move helper functions to a single js file instead of multiple~~
- [ ] Move helper functions out of main.js
- [ ] Combine baani() and addSearchResult()

**Comment by bogas04** [comment]
Moving all helper to one file might not be a good idea IMO as it'll make it difficult for us to use modules later on.

**Comment by ManjotS** [comment]
ok, lets skip the first point

**Comment by bogas04** [comment]
Irrelevant.
