### ISSUE TITLE
Remember last search type across sessions

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/SikhiToTheMax-Web#123]
When user returns to the site, the last-used search type is selected

**Comment by ManjotS** [comment]
What about when they go from home->search->shabad this is the main issue
for this ticket

**Comment by navdeepsinghkhalsa** [comment]
When a user goes from search results to results, it automatically carries forward the search type and source even now. That behaviour would not change

**Comment by ManjotS** [comment]
Doesnt work in all cases as reported by users:

testing:
![image](https://cloud.githubusercontent.com/assets/644885/24064831/2513a50a-0b24-11e7-83ce-ec131a695c16.png)
![image](https://cloud.githubusercontent.com/assets/644885/24064836/2a60a044-0b24-11e7-93a7-ee2c3ba20399.png)

**Comment by bogas04** [comment]
This is fixed by using redux in dev branch.
