### ISSUE TITLE
add to help section on using sttm.co

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#127]
requires #126

**Comment by ManjotS** [comment]
sttm.ws is being moved to sttm.co now. All help should reference sttm.co

**Comment by tarunsingh5** [comment]
@maneetpaul can you add this to the help doc please

**Comment by bogas04** [comment]
Hi!

Shall I copy paste the help docs to `/help`?

**Comment by ManjotS** [comment]
Hi @bogas04 I am working on branch fix-126-help

I can handle some of the minor stuff like this so you can focus on the bigger projects.

**Comment by bogas04** [comment]
No problem at all! Was just too excited to finally contribute 😁

**Comment by tarunsingh5** [comment]
@ManjotS is this still an issue? if so can you please give detailed steps needed?

**Comment by ManjotS** [comment]
We can add a question to the help section called, "how does the url shortener work?"

basically look at twitter links for sttm.co links for pages, shabads and searches and document

**Comment by tarunsingh5** [comment]
@ManjotS @maneetpaul can you work on this - this is pretty low hanging fruit

**Comment by bogas04** [comment]
http://dev.sikhitothemax.org/help#Web-how-does-the-url-shorter-work
