### ISSUE TITLE
Old SikhiToTheMax Site

### ISSUE THREAD

**Issue by Sarabveer** [KhalisFoundation/SikhiToTheMax-Web#129]
Please allow access to the old Sikhitothemax site in the meantime, Thanks.

Preferably, maybe at old.sikhitothemax.com.

**Comment by navdeepsinghkhalsa** [comment]
Is there any particular reason you'd like to have access?

**Comment by Sarabveer** [comment]
there are some pages that were there like Rehitname I need

**Comment by ManjotS** [comment]
Maryada and rehat sections will be available on sikhitothemax.org soon. (Also Khalis Foundation has the Maryada app available)
