### ISSUE TITLE
add sample query along with "khoj" in search box

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#131]
So that users understand what is expected

ie for ang use 123
for romanized use "Jo mangay thakur apne"
etc

**Comment by bogas04** [comment]
So it would be like `Khoj - ${sampleQuery}` ?

**Comment by ManjotS** [comment]
Thinking to get rid of khoj. This came out of UX discussions on slack.

Basically to show people how to use the search bar depending on what they select in drop down.
