### ISSUE TITLE
Add sequence column to shabad table

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#142]
With shabad ids that can be out of order, we should add a sequence for doing things like next shabad.

Ideally order should be initialized with tens.. ie 10, 20, 30 so that we can reorder as necesarry.

shabads/lines with multiple ids (ie above 5000000) can be put into the same order as well.

**Comment by bogas04** [comment]
@ManjotS  VeerJee. I am seeing that there are some issues raised in STTM-Web which can't be fixed here (API/DB related). I think it'll be better suited to move this issue to [ShabadOS API](https://github.com/KhalisFoundation/ShabadOS-API).

Regarding the aforementioned issue, I guess this was fixed recently with the next/prev API change ?

**Comment by ManjotS** [comment]
yeah, my bad for putting in wrong queue. Also, we need to re-evaluate this anyway.

The API change used some queries to hack around current limitations, but still making the features available for now.
