### ISSUE TITLE
UX: Add arrow down to right side of display options

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#146]
Aman Singh [10:37 AM] 
@mkhalsa The display options button - an arrow down button next to the Display Options text may have helped users know it

**Comment by bogas04** [comment]
Is this arrow okay? ↓

**Comment by bogas04** [comment]
Pushed in 4be155ac150a38eff201d8c8d2565cd7d330ae18

**Comment by ManjotS** [comment]
I'm thinking it should match the arrow in the drop down that search uses

**Comment by bogas04** [comment]
I see.

**Comment by ManjotS** [comment]
I would rather have the triangle arrow like the drop downs. the current one feels out of place.

**Comment by bogas04** [comment]
Could you please provide HTML entity / Image for the same then ? Thanks ! I'm not really good at design as demonstrated earlier :P

**Comment by ManjotS** [comment]
If you inspect element of the drop down under the search bar, you will see
the background-image svg (its in css under select {} )

**Comment by ManjotS** [comment]
is this change in master and not in dev @bogas04 ?

**Comment by ManjotS** [comment]
its in prod but we need to change the look of the arrow

**Comment by tarunsingh5** [comment]
this is such a low priority imo

**Comment by tarunsingh5** [comment]
my view is either @ManjotS or i do this, but not @bogas04 or @navdeepsinghkhalsa
