### ISSUE TITLE
add FAQ to help section

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#148]
have it in footer

**Comment by bogas04** [comment]
What would be the content for it ?

**Comment by ManjotS** [comment]
Let's do it as a full help section (maybe theres a nodjs help website out there already?)

Topics to cover first: what does each option in drop down mean? and what does each display toggle do?

**Comment by tarunsingh5** [comment]
Maneetpaul will help with this

**Comment by ManjotS** [comment]
This is a duplicate of #126 so I am renaming this

**Comment by ManjotS** [comment]
Requires #126
