### ISSUE TITLE
consider home page background color change

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#149]
to #F5F5F5

This would make inputs stand out more

**Comment by bogas04** [comment]
Before | After
:--|:--
![localhost-8080-](https://cloud.githubusercontent.com/assets/6177621/24839674/b0a4e1fa-1d7c-11e7-9031-cbf8a4dcb5e2.png)|![localhost-8080- 1](https://cloud.githubusercontent.com/assets/6177621/24839676/b78630fa-1d7c-11e7-8ad0-5c3a3098217d.png)
![localhost-8080-search-q hhprl type 0 source all](https://cloud.githubusercontent.com/assets/6177621/24839678/bc257396-1d7c-11e7-9855-9d644467790c.png)|![localhost-8080-search-q hhprl type 0 source all 1](https://cloud.githubusercontent.com/assets/6177621/24839679/be4b24a4-1d7c-11e7-98e6-b05f558184e0.png)

**Comment by ManjotS** [comment]
I think it's your decision. Looks nice.
