### ISSUE TITLE
move drop downs above search input

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#150]

**Comment by bogas04** [comment]
Sure ?
![screen shot 2017-04-09 at 11 25 33 pm](https://cloud.githubusercontent.com/assets/6177621/24839631/001cf5fc-1d7c-11e7-9872-e6a78fc7e9df.png)

**Comment by ManjotS** [comment]
yeah, UX sevadars requested this. What has happened is a number of users don't understand that they can click and select things, so they complain that theres no english search etc. Another suggestion with this was to round the corners of the select box.

**Comment by ManjotS** [comment]
project management decided not to do this.
