### ISSUE TITLE
use on page error for search input

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#153]
ie if you click search without 3 letters .. some red or orange text specifies them to do it and goes away on keydown

**Comment by bogas04** [comment]
How about using [HTML5](http://caniuse.com/#search=pattern) for this ?

```
pattern=".{3,}"
required
title="3 characters minimum"
```

![screen shot 2017-04-09 at 11 05 39 pm](https://cloud.githubusercontent.com/assets/6177621/24839516/91c77caa-1d79-11e7-9180-0cafb02c7f32.png)


![screen shot 2017-04-09 at 11 06 11 pm](https://cloud.githubusercontent.com/assets/6177621/24839512/7588ff0a-1d79-11e7-8d4b-5fdce07156e2.png)

**Comment by ManjotS** [comment]
Awesome

**Comment by ManjotS** [comment]
Please keep #132 in mind before closing this
