### ISSUE TITLE
rename first letter search in drop down

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#154]
First letter of each word (Gurmukhi)

**Comment by bogas04** [comment]
How about `Initials of each word (Gurmukhs)`

**Comment by ManjotS** [comment]
To native english speakers initials doesn't make sense. Initials imply 
first letters of a name, and usually of a person. Any other use of the 
word initials doesn't make sense in most western english dialects.
