### ISSUE TITLE
dev - ang search broken from search page

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#157]
Issue: When searching ang on search page get "no results found"

Reproduce:
Go to home page
Type 547 in the search bar
Select Ang in type drop down
Search

Results show.

Now type 548 in search box
(ang is already selected, dont touch it)
Hit search or enter
"no results found"

**Comment by ManjotS** [comment]
it looks like the redirection to ang was broken for search type 5. (if type is 5 it goes to ang instead of search from home page) recent deploy to dev made it so search always redirects to search not to ang for type 5

@bogas04

**Comment by ManjotS** [comment]
This is because the code in main.js:updateSearchAction isn't running. Can this be fixed?

**Comment by ManjotS** [comment]
This issue is effecting all search types because that method isnt run

**Comment by ManjotS** [comment]
This is related to #159

**Comment by bogas04** [comment]
Sorry for late response, could you test it on dev now ? I've fixed it.

**Comment by ManjotS** [comment]
@bogas04 I am not sure if your fix triggers the same actions as updateSearchAction (as it should), but its introduced regressions.

Clicking search button doesn't work after initial ang search.
Display options get reset.
Fonts aren't changed in the input. (ang, english, romanized searches)
Full word gurmukhi throws facing some issues.
