### ISSUE TITLE
Add more key buttons to the keyboard

### ISSUE THREAD

**Issue by inderpreet99** [KhalisFoundation/SikhiToTheMax-Web#160]
ਓ is not shown in the drawer-keyboard. Experienced STTM users may know that shift-e gives it to us. However for beginners, it would be nice to have it be listed in the drawer-keyboard.

Shabads like ਓਇ ਸਾਜਨ ਓਇ ਮੀਤ ਪਿਆਰੇ ॥ become difficult to search if one does not know about the shift-E trick.

I would also suggest adding ॥ as a possible keyboard key. I've used it as a quick trick to getting shabads of which starting first letters I may not know. For example, if I couldn't find ਓ, I may search using ਮਪ॥. The search already works ([ref](https://www.sikhitothemax.org/search?q=mp%5D&type=1&source=all)). Though it is not the best example to show this case, since we still get a lot of search results.

**Comment by tarunsingh5** [comment]
open oora is there but being hidden by #211
