### ISSUE TITLE
if only one result, i feel lucky

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#177]
if there is only one result, skip the search result page and redirect directly to shabad

**Comment by navdeepsinghkhalsa** [comment]
@ManjotS I don't think this is intuitive. If it's not the Shabad that the user is looking for, the user is left confused looking for the line they searched for

**Comment by ManjotS** [comment]
@navdeepsinghkhalsa what if theres a banner on top that says "This was the only shabad found for xyz"
