### ISSUE TITLE
Allow users to change color of text/background

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/SikhiToTheMax-Web#178]
How can i change the gurbani text of output ?

**Comment by bogas04** [comment]
@ManjotS @navdeepsinghkhalsa could you please tell if we should prioritize this, or if we would give this feature ever ? I guess we can add a dark mode at least.

**Comment by ManjotS** [comment]
This issue is for the desktop app. This repo is for the website.

The ticket is already open in the destop app repo and significant work has been done on it by @navdeepsinghkhalsa . I think he just needs to expose a few more settings.
