### ISSUE TITLE
Source T is not recognized

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#181]
Please ensure Bhai Nand Lal Jee Thankhanama is recognized.

**Comment by ManjotS** [comment]
https://github.com/bogas04/khajana-js/pull/2

**Comment by ManjotS** [comment]
source T is now source R

**Comment by bogas04** [comment]
Is it still an issue?

**Comment by ManjotS** [comment]
works http://dev.sikhitothemax.org/shabad?id=31000&q=pkn&&&source=R&highlight=402704
