### ISSUE TITLE
Add select all button for Shabads view

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#183]
Why not ? It'll be hand for mobile users for sure.

**Comment by SukhmanpreetSingh** [comment]
How can i change the gurbani text ?

**Comment by bogas04** [comment]
Hi @SukhmanpreetSingh, could you please explain what you want to change ?

**Comment by SukhmanpreetSingh** [comment]
i want to change the gurbani color and bg color in desktop version

**Comment by bogas04** [comment]
I'm sorry @SukhmanpreetSingh Jee, we don't support that. If you tell me what colors you want, I can make a theme for you which you can apply only for your desktop

**Comment by SukhmanpreetSingh** [comment]
plz add this option in desktop version .... option to change color custom

**Comment by ManjotS** [comment]
@bogas04 what do you mean? what does it do?

**Comment by bogas04** [comment]
Select entire content of the shabad.
