### ISSUE TITLE
display prefs still not persisting (search results)

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#189]
Navdeep Singh [8:42 PM] 
@mkhalsa I'm not seeing the issue with display prefs not persisting. Could you please provide steps to reproduce?

Manjot Singh [8:42 PM] 
Firefox 57

[8:43] 
Search something, show translations, close and reopen or search for something else

Navdeep Singh [8:45 PM] 
Persisting for me

[8:47] 
Ah. You're talking about the search results page

Manjot Singh [8:48 PM] 
Yes

Navdeep Singh [8:48 PM] 
Could you write up a bug report on GitHub?

Manjot Singh [8:48 PM] 
Ok

new messages
Navdeep Singh [8:48 PM] 
:pray:

**Comment by ManjotS** [comment]
@bogas04 was this fixed?

**Comment by tarunsingh5** [comment]
was resolved by #239
