### ISSUE TITLE
tweet and copy hovers not working

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#196]
## What went wrong ?
tweet and copy of lines not working in firefox

## What should have happened instead ?
should tweet or copy

## How can authors of this project cause the issue to occur on their systems ?
use firefox, load a shabad or ang, hover over a line and click tweet or copy

## What were you trying the project on ?

  - Browser: firefox
  - Browser Version: 57
  - Operating System: Mac

**Comment by tarunsingh5** [comment]
works on chrome, ie, not on FF

**Comment by navdeepsinghkhalsa** [comment]
GitHub uses this: https://github.com/zeroclipboard/zeroclipboard

**Comment by bogas04** [comment]
https://github.com/KhalisFoundation/SikhiToTheMax-Web/pull/276 Might give us a common utility function to do copy pasting. Anyway, this textarea part of code is really bad.
