### ISSUE TITLE
on screen keyboard: biharee closes and breaks keyboard

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#211]
## What went wrong ?
clicking this closes and breaks the keyboard requiring reload ![image](https://user-images.githubusercontent.com/644885/35023724-c4f20e2e-faf0-11e7-9ed6-3ac186ba828b.png)

**Comment by navdeepsinghkhalsa** [comment]
Fixed by PR #232
