### ISSUE TITLE
Copying gurmukhi the spaces are missed off

### ISSUE THREAD

**Issue by visionthroughdesign** [KhalisFoundation/SikhiToTheMax-Web#217]
## What went wrong ?
When copying from the website it fails to space out the Gurmukhi. Spacing within transliteration and Meaning works without issue. Issue exists when you chose unicode also.

EG.
ਗਾਵੈਕੋਤਾਣੁਹੋਵੈਕਿਸੈਤਾਣੁ॥
Gaavai Ko Taann Hovai Kisai Taann ||
Some sing of His Power-who has that Power?

## What should have happened instead ?

[Unicode Enabled]
ਗਾਵੈ ਕੋ ਤਾਣੁ ਹੋਵੈ ਕਿਸੈ ਤਾਣੁ ॥
gaavai ko thaan hovai kisai thaan |
Some sing of His Power-who has that Power?

[Unicode Disabled]
gwvY ko qwxu hovY iksY qwxu ]
gaavai ko thaan hovai kisai thaan |
Some sing of His Power-who has that Power?

## How can authors of this project cause the issue to occur on their systems ?

  1. Search bani from the website, Issue also occurs with Hukamnama/Searches or Random Shabad
  2. Copy Paste the Gurbani line from the website, when pasting all formatting would be removed. 

## What were you trying the project on ?
  - Browser: Google Chrome 
  - Browser Version: Version 63.0.3239.132 (Official Build) (64-bit)
  - Operating System: MAC OSX El Captain - 10.11.6 (15G1421)

**Comment by tarunsingh5** [comment]
confirmed that this happens

**Comment by ManjotS** [comment]
@bogas04 this is a regression introduced by split view. 

It behaves differently per browser. In firefox it inserts line returns. Direct paste from unicode:

ਤੂ
ਠਾਕੁਰੋ
ਬੈਰਾਗਰੋ
ਮੈ
ਜੇਹੀ
ਘਣ
ਚੇਰੀ
ਰਾਮ
॥

**Comment by visionthroughdesign** [comment]
Currently it structures the gurbani line in the following manner, with each word being in its own div so when you copy from it it doesn't try to add spaces after every word.

<div class="gurlipi"><div class="akhar">Kojq</div><div class="akhar">Kojq</div><div class="akhar">mY</div><div class="akhar">iPrw</div><div class="akhar">Kojau</div><div class="akhar">bn</div><div class="akhar">Qwn</div><i>] </i></div>

Would a structure change to the following be a more efficient way to structure the data?

<div class="gurlipi akhar" style="font-family: GurbaniAkharThick;">Kojq Kojq mY iPrw Kojau bn Qwn ]</div>

**Comment by bogas04** [comment]
@visionthroughdesign Thank you so much for the feedback and insight in the implementation. However, your solution wouldn't quite work well with Larivaar option. Anyway, I'm working on a solution to support everything without causing massive change in codebase.
