### ISSUE TITLE
Searching for Ang outside of 1-1430 returns incorrect Gurmukhi Error

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/SikhiToTheMax-Web#238]
<img width="852" alt="screen shot 2018-01-25 at 10 53 30 pm" src="https://user-images.githubusercontent.com/35271830/35428241-c5edc122-0222-11e8-9354-725079d15d62.png">

## How can authors of this project cause the issue to occur on their systems ?
https://www.sikhitothemax.org/ang?type=5&source=all&ang=1431

## What were you trying the project on ?
  - Browser:Chrome
  - Operating System: OSX

**Comment by lbk003** [comment]
@tarunsingh5 What is the correct message you expect?

**Comment by tarunsingh5** [comment]
This panna does not exist in this source

**Comment by bogas04** [comment]
Closing in favour of #116
