### ISSUE TITLE
prod loading dev resources

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#241]
## What went wrong ?
web console throws:
Blocked loading mixed active content “http://dev.sikhitothemax.org/assets/fonts/GurbaniAkharHeavyTrue.ttf?v=1”
[Learn More]
www.sikhitothemax.org
Blocked loading mixed active content “http://dev.sikhitothemax.org/assets/fonts/fontawesome-webfont.woff2?v=4.7.0”
[Learn More]
www.sikhitothemax.org
Blocked loading mixed active content “http://dev.sikhitothemax.org/assets/fonts/AnmolLipiSG.ttf?v=1”
[Learn More]

## How can authors of this project cause the issue to occur on their systems ?

  1. load sikhitothemax.org
  2.
  3.

## What were you trying the project on ?

  - Browser: Firefox
  - Browser Version: 58
  - Operating System: Mac

**Comment by bogas04** [comment]
Do we have this issue now?
@ManjotS
