### ISSUE TITLE
Clicking outside of keyboard should close keyboard

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/SikhiToTheMax-Web#246]
Clicking on an area outside the keyboard when the keyboard is open should close the keyboard

**Comment by bogas04** [comment]
There are at least two ways of implementing this:

* GurmukhiKeyboard can add an overlay div which onClick closes it.
* You add an evenListener to window and when triggered, it sees if the target of click is the keyboard, or something inside it, or just any other place, and we close it in the latter case. There's an API in DOM called closest that can be used to check the 2nd case. Remember to remove the event listener on componentWillUnmout life cycle event of the GurmukhiKeyboard.

I can mentor if required.
