### ISSUE TITLE
Source is undefined in footer

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/SikhiToTheMax-Web#261]
## What went wrong ?
When using the forward or backward icons in the footer, source is coming as undefined and if you are in Dasam Bani shabad view, forward / backward icon takes you to SGGS.

## What should have happened instead ?
Footer forward / backward icons should work the same as how they do in header.

## How can authors of this project cause the issue to occur on their systems ?
  1. Open this link: https://www.sikhitothemax.org/ang?ang=13&source=D
  2. Click on next or backward in the footer
  3. You should see URL has source=undefined
  4. When you click on the icons, it switches source to SGGS

## What were you trying the project on ?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by tarunsingh5** [comment]
confirmed - this only happens when you click back or forward using the footer - not w/ the header arrows

**Comment by bogas04** [comment]
@skyhiagency has tested it on dev and it seems this error isn't occurring anymore.

**Comment by skyhiagency** [comment]
Cannot trace the issue in dev environment
