### ISSUE TITLE
Larivaar assist skips last word sometimes

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#264]
## What went wrong ?
if the last word is supposed to be orange, it stays black in larivaar assist mode

## What should have happened instead ?
should be orange

## How can authors of this project cause the issue to occur on their systems ?

  1. visit a shabad
  2. click larivaar
  3. click larivaar assist

**Comment by tarunsingh5** [comment]
this seems to be fixed now (i did multiple searches and can't find any instances) - can you confirm?

**Comment by ManjotS** [comment]
we found this at my house remember? it doesn't color the last word.

**Comment by tarunsingh5** [comment]
i think it is no longer an issue (as in i cant find it happening) - perhaps this was due to how we treated divs differently?

**Comment by bogas04** [comment]
What should be done with this? Is it still an issue with `dev` branch?

**Comment by tarunsingh5** [comment]
i havent seen this be an issue in the last few months - going to close for now
