### ISSUE TITLE
MSFT Edge automatically adds a cross button to search input

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#265]
Since we are using `[type="search"]` on our input field, Microsoft Edge automatically adds a cross/clear button. We should hide it (probably by not using `[type="search"]`, not good), or hide ours (feature detection? UA agent? not good either)

**Comment by tarunsingh5** [comment]
Was this fixed in dev?

**Comment by bogas04** [comment]
It's merged in dev, but not deployed yet I guess
