### ISSUE TITLE
Highlight tukk in shabad depending on search result

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/SikhiToTheMax-Web#306]
## What went wrong ?
Takes time to find the bit of a shabad I was searching for.

## What should have happened instead ?
I should be able to easily see the tukk in the shabad that I searched for. The page should also scroll down automatically to the tukk that was searched for.

## How can authors of this project cause the issue to occur on their systems ?

  1. Search for a tukk in Gurbani as normal
  2. Open results.
  3. No highlighting for tukk searched is available.

## What were you trying the project on ?

  - Browser:
  - Browser Version:
  - Operating System:

**Comment by bogas04** [comment]
I really want this. Will take it up this week!

**Comment by bogas04** [comment]
<img width="637" alt="screen shot 2018-03-05 at 4 53 48 pm" src="https://user-images.githubusercontent.com/6177621/36972628-d92643d6-2095-11e8-9297-491bcf190adb.png">

Didn't go for orange as it might be too distracting.
