### ISSUE TITLE
Insert meta-tags for all STTM webpages.

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/SikhiToTheMax-Web#317]
## What went wrong ?
Google is not giving much weight to STTM for keywords because our meta tags are non-existent.

## What should have happened instead ?

Add meta tags:-
Title
Keywords
Description
Author
Copyright
Robots

**Comment by jhbsk** [comment]
We should be careful about this, as making it look spammy can also end up becoming a negative SEO factor. Worth getting an SEO expert's opinion: http://d2eeipcrcdle6.cloudfront.net/guides/Moz-The-Beginners-Guide-To-SEO.pdf

**Comment by bogas04** [comment]
This is kinda a huge part as we need to fetch these details at server end and create the meta tags statically. 

Server side rendering will help us a lot with this one, which I intend to take up soon. :P

**Comment by bogas04** [comment]
Closing in favour of #333
