### ISSUE TITLE
Add a step to the build instructions to access dev environment

### ISSUE THREAD

**Issue by lbk003** [KhalisFoundation/SikhiToTheMax-Web#327]
## What went wrong ?
Readme file does not step on how to access the local dev environment

## What should have happened instead ?
Add the step. 

## How can authors of this project cause the issue to occur on their systems ?
  1. Read the [build instructions](https://github.com/KhalisFoundation/SikhiToTheMax-Web) 

## What were you trying the project on ?
Should not by impacted by this, but for sake of completion:
  - Browser: Chrome
  - Browser Version: Version 65.0.3325.106 (Official Build) beta (64-bit)
  - Operating System: MacOS High Sierra 10.13.3 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.106 Safari/537.36

**Comment by ManjotS** [comment]
@bogas04 why was this closed without a note?

**Comment by bogas04** [comment]
This was merged in master and dev. 

https://github.com/KhalisFoundation/SikhiToTheMax-Web/commit/3ef832a0ff6750abad3c8dee679cecae331274f2
