### ISSUE TITLE
Improve english translations

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#339]
Please select which platform you are using:-
Web Version

Feedback Type
Enhancements

What went wrong?
English translation provided is not all that great. Please consult someone who has  "giaan" wisdom, who spends thier time in the society, company of saints and in the process of providing English translation of Gurbani, respected Punjabi translation such as Prof Sahib Singh's Darpan is consulted and checked too. For otherwise it's the blind leading the blind. Sorry to use such strong language. This is a huge undertaking. God bless. 
 
What should have happened instead?

    
How can the issue be recreated by our team?
The English translation is needs to be reviewed very carefully - someone who has attained wisdom, in the company of saints, etc who is a true GUR- SIKh, meaning who knows the teachings understands the teachings of our GURUS. And the ENglish translation should be checked against a respectable source, like Prof Sahib singh ji,Gurbani Darpan. It's very important that the right translation is put outthere, so the young and old, English speaking have a better clearer understanding of the teachings left by our Great Gurus. I often check out shabads in sikhi to max, i'll give an example here. page 109 (it's actually page 110). First 2 lines: karam hoe satguru milaye. Sewa surat shabad chit lae. The English translation is totally incorrect! it's thru good fortune one meets a satguru: one meditates, concentrates mind on the shabad. Please please do something. The entire English needs a thorough going thru. I find Prof Sahib singh Darpan, very good source. A few places (on the rare instance) it may not be as clear as it should be, but overall, it's excellent, very detailed and clear. Also, it would be great if viewers know which source is being used for both the Punjabi and English translations provided in Sikhi to the Max. This is a huge project, but if we do not aim to get the translations as close to the message our Great Gurus meant to provide, then all the technical know how is of no use. as the whole point is to provide readers with better understanding of the Gurbani and  making it easily accessible. Very very important that translation is given utmost importance. We are disrespecting the Guru's teachings if we do not provide good translation (both in Punjabi and English). thank you for reading my comment. I've written quite a few times , given my feedback, never heard once back , no response at all!!! If it's too difficult to respond, no probs, but please take my suggestion into account. thanks so  much. God bless

Which web browser are using?
 

Operating System

Name
sharan kaur

**Comment by lalaagolaa** [comment]
Resolved #339

**Comment by lalaagolaa** [comment]
Closes #339

**Comment by tarunsingh5** [comment]
we are already doing this in the backend - closing this issue
