### ISSUE TITLE
Add copyright text to README and Footer

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#340]
readme should include full copyright for images in repository that are not under other licenses.

footer of site should include copyrights

**Comment by bogas04** [comment]
Can you give me the text for that? Thank you so much!

**Comment by ManjotS** [comment]
license text: 

All images and assets not covered under other licenses are covered under full Copyright &copy; 2018 Khalis Foundation

Footer:
Copyright &copy; 2018 Khalis Foundation, SikhiToTheMax Trademark SHARE Charities, UK

**Comment by bogas04** [comment]
The footer text is really huge.
