### ISSUE TITLE
Help/Web: How do I share a shabad and use the link shortener?

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/SikhiToTheMax-Web#342]
**How do I share a shabad and use the link shortener?**

Each shabad has a unique URL that can be shared online. Rather than copying a long URL, we automatically shorten it to something more shareable. You can do this by clicking any of the social media icons in the shabad view, or pressing the last icon to copy the link to your clipboard. 

![image10](https://user-images.githubusercontent.com/10658257/37866677-59e30072-2f64-11e8-89f2-37988bc2a179.png)

Additionally, for more advanced ways of using the link shortener, you have the following options:

- In case of a shabad, say ਮੇਰੇ ਸਾਹਾ ਮੈ ਹਰਿ ਦਰਸਨ ਸੁਖੁ ਹੋਇ ॥ ਹਮਰੀ ਬੇਦਨਿ ਤੂ ਜਾਨਤਾ ਸਾਹਾ ਅਵਰੁ ਕਿਆ ਜਾਨੈ ਕੋਇ ॥ ਰਹਾਉ ॥, the shabad id is 2555, and the short URL is http://sttm.co/s/2555
- In case of ang, for example ang 12 of Guru Granth Sahib Jee, the short URL is http://sttm.co/a/12
- In case of hukamnama, the short URL is http://sttm.co/h
- In case of random shabad, the short URL is http://sttm.co/r _or_ http://sttm.co/random

**Comment by ManjotS** [comment]
please include random too sttm.co/r or sttm.co/random

**Comment by maneetpaul** [comment]
added!
