### ISSUE TITLE
Help/Common: How do I use a QWERTY keyboard to type Gurmukhi?

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/SikhiToTheMax-Web#346]
Please reference the following keyboard map: 
<img width="566" alt="screen shot 2018-03-24 at 1 51 22 pm" src="https://user-images.githubusercontent.com/10658257/37867149-a0d948c8-2f6a-11e8-8fc5-67b7df6f0a1d.png">
_### Keyboard map courtsey of http://www.discoversikhism.com/_

**Comment by ManjotS** [comment]
this is exactly what I was thinking @maneetpaul

**Comment by bogas04** [comment]
I would like this to be implementated as a React component itself with an input field where user can test and play. More interactive.
Something like an Input where user types qwerty and sees gurmukhi in it, and the grid below for reference, maybe we can light up the key user pressed in the grid to make it fancy :D.
