### ISSUE TITLE
Bring back SGGS Index page

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#359]
We used to have SGGS index page. (/GGSIndex.asp)
Let's bring it back, we can have a new route for it and other indexes.

**Comment by bogas04** [comment]
Since this is pretty static, we can create a JSON for this for now.

**Comment by ManjotS** [comment]
our ids dont match up to sttm2.. so we will need to update it first.

**Comment by tarunsingh5** [comment]
let's use this for the index and just point to the ang #

http://www.sikhiwiki.org/index.php/Sikh_Ragas

**Comment by tarunsingh5** [comment]
Dasam Granth Index Here - use Column E as your guide

https://docs.google.com/spreadsheets/d/1UirTRcyMORrLoaaoi8lvFZK6_ngzYx8UuUPFYdplveg/edit?usp=sharing
