### ISSUE TITLE
/shabad should redirect to random shabad.

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#364]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Random shabad is not working. Earlier it would give us a vaak randomly. Now it's showing a blank screen.i am using Chrome on Android phone. 
 
What should have happened instead?

    
How can the issue be recreated by our team?
Type random shabad on Google and try opening the Sikhi to the max page. 

Which web browser are using?
Chrome 

Operating System
Other

Name
Amardeep Singh

**Comment by bogas04** [comment]
![screenshot_20180327-091549](https://user-images.githubusercontent.com/6177621/37945798-9414a420-319f-11e8-87aa-2c76c82d9d51.jpg)

**Comment by bogas04** [comment]
Just realized, in case of error, no Links work.
