### ISSUE TITLE
Not able to find random Shabad

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#378]
Please select which platform you are using:-
Web Version

Feedback Type
How this situation will clear out 

What went wrong?
Not able to find random shabd Please clear that unusual problem 
 
What should have happened instead?

    
How can the issue be recreated by our team?
If any sawadar is there who can fix it

Which web browser are using?
Chrome Chrome 

Operating System
Other

Name
Jasbir  Kaur

**Comment by bogas04** [comment]
Need more info here. I guess it loads fine for most users, right?

**Comment by bogas04** [comment]
@ManjotS is there a way to contact these people?

**Comment by ManjotS** [comment]
Yes. Assign ticket to me or tarun and we can pull email and send. If you
have questions tag us with the question to ask.

**Comment by tarunsingh5** [comment]
responded to the user with the following:

Bhenji please visit www.sttm.co/r - this will take you to a random shabad. alternatively you can click the button that says "random shabad" in the top right on desktop or click on the hamburger menu and click "random shabad" on mobile.
