### ISSUE TITLE
Web User That unusual problem is still have to check 

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#381]
Please select which platform you are using:-
Web Version

Feedback Type
That unusual problem is still have to check 

What went wrong?
Not able to find random shabd To clear the site 
 
What should have happened instead?
I want to find so it should be done 
    
How can the issue be recreated by our team?
Please if any sawadar is there who can fix it.

Which web browser are using?
Chrome 

Operating System
Other

Name
Jasbir  Kaur

**Comment by bogas04** [comment]
Can we contact Jasbir Kaur? We need to get more information about this.

This is second report about same issue #378
