### ISSUE TITLE
Web User Thank you. 

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#382]
Please select which platform you are using:-
Web Version

Feedback Type
Thank you. 

What went wrong?
Its clear Clear
 
What should have happened instead?
Hope want happen again.
    
How can the issue be recreated by our team?
Thank you all.Clear

Which web browser are using?
Chrome Sikhi to the max

Operating System
Other

Name
Jasbir  Kaur

**Comment by bogas04** [comment]
We really need to talk to Jasbir Kaur. Can't understand what she really wants. 🤷🏽‍♂️
