### ISSUE TITLE
add ang viewer

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#40]
I feel we should have a way to view one entire ang of any source. The API does support it so it shouldn't be that hard, I guess the renderShabad method should `just work`.

**Comment by ManjotS** [comment]
I agree. My thought is lets just add Ang to the drop down and when its selected, only allow numbers in search input.

**Comment by bogas04** [comment]
I've created a commit 04e6763de221cb16e5e35da9849a4f8a8f199b49, do I need to do anything so that it appears on dev webpage ?

**Comment by ManjotS** [comment]
upload to ftp under www/dev/

**Comment by bogas04** [comment]
Okay I'm at work right now, won't be able to do that (R&D stuff). 

I tested the `renderShabad` method (after above commit), it seems to be working just fine. 

```js
  const url = buildApiUrl({ ang: 123, source: 'D' });

  // clear contents of shabad Node
  $shabad.innerHTML = '';  

  // Fetch from API (You can use jQuery's ajax)
  fetch(url)
    .then(r => r.json())
    .then(e => renderShabad(e.shabads));
```

So I think all we need to do is update `shabad.js` to see if it's passed ang and source in query params, and based on that we can simply just build the API url differently. Or we can have a different page altogether for a better looking route. This concludes the viewer part, to get to it we've two options:

 * From search results page, we can create a hyperlink once above part is done.
 * From home page (as per your suggestion we can just have Ang option in first dropdown and allow only numeric input that too in range of ang-spread.

I'll try to do it once I'm back home.
