### ISSUE TITLE
Larivaar Assist doesn't work for highlighted tuk in dark mode

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#404]
<img width="879" alt="screen shot 2018-04-09 at 12 53 19 pm" src="https://user-images.githubusercontent.com/6177621/38484670-01442caa-3bf5-11e8-9737-19445c338326.png">

Maybe we can highlight the tuk by showing a border-left

<img width="853" alt="screen shot 2018-04-09 at 12 50 44 pm" src="https://user-images.githubusercontent.com/6177621/38484693-098c3a88-3bf5-11e8-9c32-5fcf65aa8935.png">
<img width="852" alt="screen shot 2018-04-09 at 12 51 14 pm" src="https://user-images.githubusercontent.com/6177621/38484695-0b4a1200-3bf5-11e8-95f8-06341403c4d9.png">

**Comment by ManjotS** [comment]
use blue

**Comment by bogas04** [comment]
Blue doesn't look that good on black actually

**Comment by irvanjit** [comment]
It also doesn't work for the tukhs shown in the shabad results screen @bogas04

**Comment by bogas04** [comment]
Toast should also be updated.

And we can also adjust the theme color to update statusbar on phones.
