### ISSUE TITLE
Grey out the next/previous button instead of hiding them

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#405]
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
Sometimes the next page doesn't show.
 
What should have happened instead?
There should be a next page button.
    
How can the issue be recreated by our team?
Try searching the English word "work"

Which web browser are using?
Chrome Latest

Operating System
Mac OS

Name
Japnam Singh

**Comment by bogas04** [comment]
Coz there's no next Shabad. @saintsoldierx do we need to make next button grey instead?

**Comment by saintsoldierx** [comment]
Yes I would do that.
