### ISSUE TITLE
Nothing renders on Safari

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#407]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Site loads completely blank on iOS for about the last 4 days. The only thing that loads is the bottom bar. I've tried requesting the desktop version and also tried turning to landscape, but none work.
 
What should have happened instead?

    
How can the issue be recreated by our team?
Try to load site on iOS using Safari or Chrome

Which web browser are using?
Safari 

Operating System
Other

Name
First Last

**Comment by bogas04** [comment]
What version of Safari are they using? Maybe something is broken there.

**Comment by tarunsingh5** [comment]
was not able to replicate w/ multiple tests
