### ISSUE TITLE
Show more results not working

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#412]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Won't go to next page or show more result.
 
What should have happened instead?
Shown more results
    
How can the issue be recreated by our team?
Search eko in gurmukhi.

Which web browser are using?
Chrome Latest Android version

Operating System
Other

Name
Japnam Singh

**Comment by tarunsingh5** [comment]
confirmed this is an issue

to test this go here:
https://www.sikhitothemax.org/search?q=eyko&type=2&source=all

you'll see that the last result is on Ang 72

but if you change the source to Dasam Bani, you can see that there are results that are not showing up:

https://www.sikhitothemax.org/search?q=eyko&type=2&source=D
