### ISSUE TITLE
Read search type, query and source from query params first and then from localStorage

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#427]
## What went wrong ?
visit a search such as https://www.sikhitothemax.org/search?q=gurisK%20mIq&type=2&source=all and it shows ang in drop down and keeps spinning (no error)

## What should have happened instead ?
drop down should be type 2, full word gurmukhi

## What were you trying the project on ?

  - Browser: FF (newest)
  - Browser Version: 
  - Operating System: mac HS

**Comment by bogas04** [comment]
It shows ang for you as it was in localStorage, need to update code to give priority to query params first. 

Secondly, it keeps spinning coz API response takes time, if you wait for few seconds, you'll get the results.
