### ISSUE TITLE
Embed option

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/SikhiToTheMax-Web#43]
Allow user to embed Panktee(s) or Shabad to their website.
Use blockquote with Unicode followed by async script to style and add display option toggles

See Twitter embed code

> &lt;blockquote class="twitter-tweet" data-lang="en">&lt;p lang="en" dir="ltr">Now that the mad shopping is over let&#39;s focus on &lt;a href="https://twitter.com/hashtag/GivingTuesday?src=hash ">#GivingTuesday&lt;/a>&lt;br>Help Khalis connect Sangat with Gurbani thru tech. &lt;a href="https://t.co/J6LOqD1uKI">https://t.co/J6LOqD1uKI &lt;/a>&lt;/p>&mdash; Khalis Foundation (@khalisfound) &lt;a href="https://twitter.com/khalisfound/status/803660024325107712">November 29, 2016&lt;/a>&lt;/blockquote>
> &lt;script async src="//platform.twitter.com/widgets.js" charset="utf-8">&lt;/script>

**Comment by bogas04** [comment]
* [ ] Dynamic Import `getEmbed` as it's a heavy function
* [ ] Generated code is very heavy, maybe we should do data-fetching in the async js function, but then we need to handle ajax/banidb thingy.
* [ ] Minify embed code.

Screenshots:
* `</>` Embed option

<img width="539" alt="screen shot 2018-03-19 at 12 05 23 am" src="https://user-images.githubusercontent.com/6177621/37569499-491a3e72-2b09-11e8-8a33-9149de50482f.png">

* Embedded Snippet
<img width="538" alt="screen shot 2018-03-19 at 12 06 35 am" src="https://user-images.githubusercontent.com/6177621/37569509-6adac87e-2b09-11e8-8f3f-0c5f93931815.png">

**Comment by bogas04** [comment]
@navdeepsinghkhalsa I'm no designer but this is what I could come up with.

**Comment by ManjotS** [comment]
amazing

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/37634885-a8e08184-2bb5-11e8-801d-25f419d3ad4b.png)
![image](https://user-images.githubusercontent.com/27791330/37634905-c8a990dc-2bb5-11e8-9e4a-07b716185406.png)

**Comment by bogas04** [comment]
@saintsoldierx So cool!

**Comment by bogas04** [comment]
Bubble one is bit too much to implement, I've two variants here:

|Gradient | Solid |
|:--|:--|
![localhost_8080_embed html 2](https://user-images.githubusercontent.com/6177621/37874249-67e5df92-3049-11e8-9033-20dccea7cb61.png) | ![localhost_8080_embed html 3](https://user-images.githubusercontent.com/6177621/37874250-68238752-3049-11e8-9b90-7021c4be1c50.png)

**Comment by bogas04** [comment]
@tarunsingh5 @saintsoldierx @ManjotS please vote or suggest new design. 
Gradient one is implemented in [embed branch](https://github.com/KhalisFoundation/SikhiToTheMax-Web/tree/embed).

**Comment by tarunsingh5** [comment]
@bogas04 lets go w/ gradient
