### ISSUE TITLE
do not auto search with searchtype drop down change

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#441]
## What went wrong ?
when I am searching, search type drop down changes auto search. This is usually undesired.

## What should have happened instead ?
To reduce error exposure, we shouldn't auto search unless the search input was first changed. Otherwise we are adding more load to the api for no reason (ie searching first letter search 123).

## How can authors of this project cause the issue to occur on their systems ?

  1. search for ang 123
  2. change drop down to first letter search
  3. error

**Comment by bogas04** [comment]
This was a requested feature: https://github.com/KhalisFoundation/SikhiToTheMax-Web/issues/143
