### ISSUE TITLE
Typo in seheskriti

### ISSUE THREAD

**Issue by taranjs** [KhalisFoundation/SikhiToTheMax-Web#450]
![](https://ibin.co/41JcvBxfD2kz.jpg)

Just noticed this typo in English which doesn't appear when I browse through to seheskriti baani via index

**Comment by bogas04** [comment]
Thank you so much for finding the bug. We're fixing it.

**Comment by taranjs** [comment]
I wish to contribute myself as well. Learning git but struggling to find time at the moment. Still I hope I would be able to make some contributions on and off.

4 years ago it was my dream to have something like this, when STTM desktop had gone quite old and I personally used it for presenting in guru ghars and knew the limitations in and out. Now that I found you guys are doing a great job, I want to do my bit in whichever way I can.

**Comment by ManjotS** [comment]
Fixed

```
MariaDB [khajana_khajana]> select * from Raag where RaagId=36\G
*************************** 1. row ***************************
      RaagID: 36
RaagGurmukhi: slok shsik®qI
 RaagUnicode: ਸਲੋਕ ਸਹਸਕ੍ਰਿਤੀ
 RaagEnglish: Salok Sehskritee
     StartID: 1353
       EndID: 57607
RaagWithPage: Salok Sehskritee (1353-1360)
1 row in set (0.00 sec)
```
