### ISSUE TITLE
Web User option problem

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#472]
Please select which platform you are using:-
Desktop Version

Feedback Type
option problem

What went wrong?
Unhandled exception has occured. Not open the option of search Guru granth sahib and Dasam granth etc.not open
 
What should have happened instead?

    
How can the issue be recreated by our team?
plz tell me how cam i solve it.

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Sandeep Singh

**Comment by bogas04** [comment]
Can we contact the user? @tarunsingh5 @ManjotS

**Comment by tarunsingh5** [comment]
based on user screenshot this is a STTM II error 

![screenshot 42](https://user-images.githubusercontent.com/35271830/40450891-d38b4568-5e91-11e8-929e-12d31315cf9b.png)
