### ISSUE TITLE
Hovering over the square app icon doesn't show it's a link

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/SikhiToTheMax-Web#475]
**Describe the bug**
When hovering over the app icon, should show a hand or pointer to tell the user it's a link. It currently does not change when user hover overs it.

**To Reproduce**
1. Go to any shabad after searching for it
2. Hover over the square app icon in top left corner
3. Notice no change of pointer

**Expected behavior**
Pointer should change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bogas04** [comment]
It is a link, no? It takes you to the homepage.

**Comment by bogas04** [comment]
Closing for now as it's intended. Even google does it this way.

![hover](https://user-images.githubusercontent.com/6177621/40589309-c8ed3dee-6208-11e8-86b0-8c0ce0d1a528.gif)
