### ISSUE TITLE
Add random hukamnama like sttm.com

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#50]
Also differentiate random vs darbar sahib

**Comment by Sarabveer** [comment]
random shabad by a server ≠ gurus hukam

**Comment by ManjotS** [comment]
rename to "Random Shabad" and "Darbar Sahib Hukamnama"

**Comment by navdeepsinghkhalsa** [comment]
Added in 75c39ee
