### ISSUE TITLE
Header split into two by colours

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/SikhiToTheMax-Web#54]
Submitted by @ManjotS 

![pasted image at 2017_01_23 08_33 am](https://cloud.githubusercontent.com/assets/23178470/22229031/070ce9f4-e18a-11e6-9b03-96a03caba387.png)

**Comment by bogas04** [comment]
Could you please elaborate on the context ?

Thank you so much!

**Comment by navdeepsinghkhalsa** [comment]
In the screenshot, there are two colours in the header, to separate the top and bottom rows. @ManjotS would like to see a darker colour for the top and keep the current one for the bottom

**Comment by ManjotS** [comment]
i dont think we should do this anymore
