### ISSUE TITLE
When larivaar mode is enabled, and translations disabled, the first line (i.e. sirlekh) cannot be highlighted

### ISSUE THREAD

**Issue by irvanjit** [KhalisFoundation/SikhiToTheMax-Web#59]

**Comment by navdeepsinghkhalsa** [comment]
@irvanjit Could you please drop a link in here for an example?

**Comment by irvanjit** [comment]
<img width="348" alt="larivaar-with-engl" src="https://cloud.githubusercontent.com/assets/1472548/22310465/55988a26-e31d-11e6-9968-8171f6c1ef8a.png">
<img width="454" alt="normal-with-engl" src="https://cloud.githubusercontent.com/assets/1472548/22310462/55956b7a-e31d-11e6-81fb-58e49ac40020.png">
<img width="340" alt="larivaar-no-engl" src="https://cloud.githubusercontent.com/assets/1472548/22310464/5596e2fc-e31d-11e6-9b1a-0d81df7b56b3.png">
<img width="349" alt="normal-no-engl" src="https://cloud.githubusercontent.com/assets/1472548/22310463/559658e6-e31d-11e6-98a0-9b70fae0ea34.png">
