### ISSUE TITLE
show a "?" on virtual keyboard, clicking on which shows the qwerty -> gurakhar mapping

### ISSUE THREAD

**Issue by vikramkhalsa** [KhalisFoundation/SikhiToTheMax-Web#62]
Not everyone knows which keys on the physical keyboard correspond to which gurmukhi letters. I was showing the beta desktop app to someone and they were struggling because they only knew how to use the popup overlay with on screen gurmukhi letters which was available in the original STTM. I think this feature should be added in a future release (at least in desktop, maybe all versions) so people can find those difficult letters such as q.

**Comment by irvanjit** [comment]
Perhaps a quick tutorial that shows the mapping on first run (and from a context menu or something)? Virtual keyboards are a lot slower to use

**Comment by bogas04** [comment]
I've added a Help section link for now.

**Comment by bogas04** [comment]
To make things less clumsy, let's just add the correct info in Help section. This will make the information shareable as a link.

**Comment by bogas04** [comment]
Okay, did that. http://dev.sikhitothemax.org/help#Web-how-to-type-gurmukhi-with-keyboard
