### ISSUE TITLE
Experiment with express backend

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#69]
I'm working on a prototype of existing source with express backend, let's see how it goes.

**Comment by bogas04** [comment]
[next](https://github.com/KhalisFoundation/SikhiToTheMax-Web/tree/next) branch deals with it.

**Comment by tarunsingh5** [comment]
hey @bogas04 is this still relevant?

**Comment by bogas04** [comment]
Nope. Nice catch.
