### ISSUE TITLE
Improve developer experience for version 1

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#73]
Right now it's hard to develop with mysql requirement and PHP quirks. Maybe we can improve experience so that it's easier to contribute.

* [x] Use package.json to have a start script (assuming developer has npm setup).
* [ ] Have a $DEV_MODE which gets around PHP as much as possible with some defaults.
* [ ] ...

**Comment by bogas04** [comment]
@navdeepsinghkhalsa please help me with this issue, if we could simply ignore SQL and fill values with defaults, it'll really help me a lot to test on my system before fixing other issues.

**Comment by ManjotS** [comment]
I think #103 will help with this
