### ISSUE TITLE
Make search bar full width in mobile mode.

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#75]
![screenshot_20170219-135645](https://cloud.githubusercontent.com/assets/6177621/23100597/593bab80-f6ab-11e6-9cab-5e7ea8fd5438.png)

**Comment by bogas04** [comment]
Still bit buggy at very low resolutions

![Gif](http://recordit.co/XEdu9sBEcz)

**Comment by ManjotS** [comment]
see my recent commits that fix this
