### ISSUE TITLE
searching source S (bhai gurdas singh) shows other sources

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#80]
theres also weird stuff in text under results https://www.sikhitothemax.org/search?q=vvgs&type=1&source=S

**Comment by bogas04** [comment]
Can you explain this ? Just to be clear, Bhai Gurdas Singh ≠ Bhai Gurdas Jee

**Comment by tarunsingh5** [comment]
did some testing and i don't think this is still an issue - @ManjotS im going to close for now, feel free to reopen if needed
