### ISSUE TITLE
Add split view

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#87]
The old site had a toggle for split view where you could read (and copy paste) the gurmukhi in a block with each other part in its own block for full shabad/ang/etc

**Comment by ManjotS** [comment]
We have multiple user reports on this

**Comment by bogas04** [comment]
@ManjotS @navdeepsinghkhalsa I need help with UI. If nothing at all, can I get a look at old website UI? Thanks!

**Comment by ManjotS** [comment]
@bogas04 basically instead of the following:

> gurmukhi1
> romanized1
> punjabi1
> english1
> 
> gurmukhi2
> romanized2
> punjabi2
> english2
> 
> gurmukhi3....

the toggle changes the page to:

> gurmukhi1
> gurmukhi2
> gurmukhi3...
> 
> romanized1
> romanized2
> romanized3...
> 
> punjabi1
> punjabi2
> punjabi3...
> 
> english1
> english2
> english3...

**Comment by bogas04** [comment]
@ManjotS 

Oh, so it's not like

| Gurmukhi | Romanized | Punjabi | English |
|:--|:--|:--|:--
g1 | r1 | p1 | e1
g2 | r2 | p2 | e2

?

**Comment by ManjotS** [comment]
no.

its seperating into a paragraph instead of line by line.

**Comment by bogas04** [comment]
Thank you so much for clarifying @ManjotS. Fix incoming!
