### ISSUE TITLE
facing some issues with romanized search

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#89]
User Report

Romanized English is not working. Previous version of Sikhi2maxx was much benefitial. Pls help - trying to search "nindiya hoye taan bekunt"

https://www.sikhitothemax.org/search?q=nindiya+hoye+taan+bekunt&type=4&source=all

**Comment by navdeepsinghkhalsa** [comment]
Fixed in Khajana
