### ISSUE TITLE
next/last shabad/ang

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#94]
User report:

There should be option to go forward from current selected shabad or backward to previous shabad when viewing a search result.

**Comment by ManjotS** [comment]
@bogas04 please prioritize

**Comment by ManjotS** [comment]
commit 196d013b514350354114b57b1ca1d11fcb543d86 adds it to shabados api, its live on dev.

**Comment by ManjotS** [comment]
if there is a next or prev navigation, we should show buttons in the header like so:

![image](https://user-images.githubusercontent.com/644885/32412425-b01b7fa0-c1b4-11e7-8e01-2059370b1085.png)

**Comment by tarunsingh5** [comment]
This is fixed in prod - closing
