### ISSUE TITLE
Bring back tabla.asp

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#97]
user report

Why tabla.asp does not work?!	wanna have tabla.asp free please if possible

**Comment by ManjotS** [comment]
I think this may be a keertan network feature request. We need to discuss if this belongs on STTM

**Comment by bogas04** [comment]
where is it? i can do it

**Comment by bogas04** [comment]
Bump. @tarunsingh5 @navdeepsinghkhalsa @ManjotS

**Comment by bogas04** [comment]
Bump two. @tarunsingh5 @saintsoldierx

**Comment by tarunsingh5** [comment]
what is this exactly?

**Comment by bogas04** [comment]
http://previous.sikhitothemax.com/tabla.asp

**Comment by tarunsingh5** [comment]
closing this issue - maybe this is an app vikram can make

**Comment by ManjotS** [comment]
@bogas04 can we have the old route redirect to http://tabla.pro please?

**Comment by tarunsingh5** [comment]
not an sttm issue - closing again
