### ISSUE TITLE
/random should just redirect to random shabad

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#99]
This will ensure:
1) we are not maintaining 2 shabad viewing interfaces (one for hukam, one for shabad/ang)
2) everything we update on shabad (ie showing author etc) is automatically there for random hukam

Don't use 301 redirects .. we just want it to be an http refresh

**Comment by ManjotS** [comment]
301 can be used with cache control or use 302 or 303

**Comment by bogas04** [comment]
00b89984ff931193de2d76f5d2557b9353f449fb should now be able to recognize `shabad?random`. Instead of using a redirect, we can simply link random page to that URL.

**Comment by bogas04** [comment]
This is fixed in dev branch.

**Comment by bogas04** [comment]
That's a good idea.

* [ ] Update URL to the shabad URL upon page load finish.
`/random` -> `/shabad?random` -> `/shabad?id=`
